public  class CLXConstants {
    //CLXPortalAPS
    public final static String PAYMENT_AMT_RESPONSE = 'Payment amount entered should be greater than zero.';
    public final static String PAYOFF_AMT_RESPONSE = 'Payoff amount should be greater than zero.';
    public final static String PAYMENT_SUC_RESPONSE = 'Payment has been recorded and will be sent for ACH processing at 3:00 PM Central Time.';
    public final static String PAYMENT_FAIL_RESPONSE = 'Payment has been recorded. ACH Business hours is closed for the day and payment will be processed on next working day.';
    public final static String PAYMENT_DUP_RESPONSE = 'Our records show an active payment request. Please contact Pioneer in case of additional payments.';
    public final static String PAYMENT_OVER_RESPONSE = 'Payment amount entered is greater than Current Loan Payoff. Please enter correct payment amount.';
    public final static String PAYMENT_CLOSED_RESPONSE = 'Loan contract has been closed/cancelled. No further payments are allowed.';
    public final static String PAYOFF_SUC_RESPONSE = 'Payoff has been recorded and will be sent for ACH processing at 3:00 PM Central Time.';
    public final static String PAYOFF_FAIL_RESPONSE = 'Payoff cannot be recorded as ACH Business hours is closed for the day. Please try again on next working day before 2:00 PM Central Time.';
    public final static String PAYOFF_DUP_RESPONSE = 'Our records show an active payoff request. Please contact Pioneer in case of any changes.';
    public final static String PAYOFF_NOT_RESPONSE = 'Payoff cannot be recorded as an active payment request exists on the contract. Please contact Pioneer in case of any questions.';
    public final static String REPAY_ACCT_RESPONSE = 'Borrower Repayment Account is not available for the contract. Please contact Pioneer for further information.';
}