public class CollectionCaseConstants {
    public static final String CASE_NUMBER = 'Case Number';
    public static final String FOLLOW_UP_DATE = 'Follow Up Date';
    public static final String VALID_FOLLOW_UP_DATE = 'Valid Follow Up Date (Date should be greater than current system date)';
    public static final String VALID_DATE = 'Valid Date (Date should be greater than current system date)';
    public static final String SUPERVISOR = 'Supervisor';
    public static final String LEGAL_USER = 'Legal User';
    public static final String BANKRUPTCY_CHAPTER = 'Bankruptcy Chapter';
    public static final String PARTIES_ASSOCIATED = 'Parties Associated';
    public static final String ACCOUNT = 'Account';
    public static final String CONTACT = 'Contact';
    public static final String BANKRUPTCY_PROOF_OF_CLAIM_FILE_BY_DATE = 'Proof of Claim File By Date';
    public static final String BANKRUPTCY_PROOF_OF_CLAIM_FILED_DATE = 'Proof of Claim Filed Date';
    public static final String PROOF_OF_CLAIM_FILED = 'Proof of Claim Filed';
    public static final String BANKRUPTCY_STATUS = 'Bankruptcy Status';
    public static final String FRAUD_ALLEGED_TYPE = 'Fraud Alleged Type';
    public static final String COLLECTABLE = 'Collectable';
    public static final String DEMAND_LETTER_ATTACHED = 'Demand Letter Attached';
    public static final String INSPECTION_DATE = 'Inspection Date';
    public static final String BUSINESS_STATUS = 'Business Status';
    public static final String OWNERSHIP_CHANGE = 'Ownership Change';
    public static final String DEMAND_LETTER_DELIVERED = 'Demand Letter Delivered';
    public static final String CONTACT_MADE_WITH_PG = 'Contact Made With PG';
    public static final String LEGAL_COUNSEL_TYPE = 'Legal Counsel Type';
    public static final String SUIT_FILED_DATE = 'Suit Filed Date';
    public static final String COURT_LOCATION = 'Court Location';
    public static final String RECEIVERSHIP_DISSOLUTION = 'Receivership/Dissolution';
    public static final String JUDGMENT_AMOUNT = 'Judgment Amount';
    public static final String JUDGMENT_DATE = 'Judgment Date';
    public static final String JUDGMENT_MATURITY_DATE = 'Judgment Maturity Date';
    public static final String JUDGEMENT_RATE_OF_INTEREST = 'Judgement Rate of Interest';
    public static final String BANKRUPTCY_FILED = 'Bankruptcy Filed';
    public static final String BAD_CONTACT_INFO = 'Bad Contact Info';
    public static final String LEFT_VOICEMAIL = 'Left Voicemail';
    public static final String GATEKEEPER = 'Gatekeeper';
    public static final String CONTACTED = 'Contacted';
    public static final String REFUSAL_TO_PAY = 'Refusal To Pay';
    public static final String CEASE_AND_DESIST = 'Cease and Desist';
    public static final String DECEASED = 'Deceased';
    public static final String DECEASED_OWNER = 'Deceased Owner';
    public static final String DECEASED_OWNER_CONFIRMED = 'Deceased Owner Confirmed';
    public static final String BANKRUPTCY_IN_PROCESS = 'Bankruptcy In Process';
    public static final String VERIFY_BANKRUPTCY_DETAILS = 'To verify bankruptcy details';
    public static final String BANKRUPTCY_PROOF_OF_CLAIM_FILED = 'Bankruptcy Proof of Claim Filed';
    public static final String BANKRUPTCY_STATUS_UPDATE = 'Bankruptcy Status Update';
    public static final String BANKRUPTCY_PLAN_PAYMENTS= 'Bankruptcy Plan Payments';
    public static final String BANKRUPTCY_PLAN= 'Bankruptcy Plan';
    public static final String BANKRUPTCY_SETTLEMENT_PLAN = 'Bankruptcy Settlement Plan';
    public static final String FRAUD = 'Fraud';
    public static final String FRAUD_ALLEGED = 'Fraud Alleged';
    public static final String FRAUD_CONFIRMED = 'Fraud Confirmed';
    public static final String SITE_INSPECTION = 'Site Inspection';
    public static final String SITE_INSPECTION_ORDERED = 'Site Inspection Ordered';
    public static final String SITE_INSPECTION_FINDINGs = 'Site Inspection Findings';
    public static final String DEMAND_LETTER = 'Demand Letter';
    public static final String REQUEST_DEMAND_LETTER = 'Request Demand Letter';
    public static final String BANKRUPTCY = 'Bankruptcy';
    public static final String CONTACT_ATTEMPT = 'Contact Attempt';
    public static final String SETTLEMENT_NEGOTIATION = 'Settlement Negotiation';
    public static final String SETTLEMENT_NEGOTIATIONS = 'Settlement Negotiations';
    public static final String SETTLEMENT_PLAN = 'Settlement Plan';
    public static final String SETTLEMENT_PLAN_REQUESTED = 'Settlement Plan Requested';
    public static final String ACCOMMODATION_REQUESTED = 'Accommodation Requested';
    public static final String ACCOMMODATION = 'Accommodation';
    public static final String SUPERVISOR_REVIEW = 'Supervisor Review';
    public static final String SUPERVISOR_FEEDBACK = 'Supervisor Feedback';
    public static final String LEGAL = 'Legal';
    public static final String LEGAL_REVIEW = 'Legal Review';
    public static final String LEGAL_FEEDBACK = 'Legal Feedback';
    public static final String MOVE_TO_LEGAL_COUNSEL = 'Move to Legal Counsel';
    public static final String MOVE_TO_INSIDE_COUNSEL = 'Move to Inside Counsel';
    public static final String MOVE_TO_OUTSIDE_COUNSEL = 'Move to Outside Counsel';
    public static final String INSIDE_COUNSEL = 'Inside Counsel';
    public static final String OUTSIDE_COUNSEL = 'Outside Counsel';
    public static final String PREPARING_SUIT = 'Preparing Suit';
    public static final String SUIT_FILED = 'Suit Filed';
    public static final String JUDGEMENT = 'Judgment';
    public static final String JUDGEMENT_AWARDED = 'Judgment Awarded';
    public static final String DEBT_CONSOLIDATOR_FOUND = 'Debt Consolidator Found';
    public static final String ATTORNEY_CONTACT = 'Attorney Contact';
    public static final String CONTACT_TYPE_ATTORNEY = 'Attorney';
    public static final Integer PROOF_OF_CLAIM_FILE_BY_DAYS = 30;
    public static final String LAST_SKIP_TRACING_DATE = 'Last Skip Tracing Date';
    public static final String SITE_INSPECTION_COMPLETED_DATE = 'Site Inspection Completed Date';

    public static final String PAYMENT_ARRANGEMENT_PROMISE_TO_PAY_TYPE = 'Promise to Pay';
    public static final String PAYMENT_ARRANGEMENT_JUDGEMENT_TYPE = 'Judgement';
    public static final String PAYMENT_ARRANGEMENT_CATCH_UP_TYPE = 'Catch Up';
    public static final String PAYMENT_ARRANGEMENT_SETTLEMENT_TYPE = 'Settlement';
    public static final String PAYMENT_ARRANGEMENT_ACCOMMODATION_TYPE = 'Accommodation';

    public static final String COLLECTION_CASE_SUB_STATUS_CATUP_MISSED = 'Catch Up Payments Missed';
    public static final String COLLECTION_CASE_SUB_STATUS_SETTLEMENT_MISSED = 'Settlement Payment Missed';
    public static final String COLLECTION_CASE_STATUS_BAD_STANDING = 'Bad Standing';
    public static final String COLLECTION_CASE_STATUS_SETTLEMENT_PLAN = 'Settlement Plan';
    public static final String COLLECTION_CASE_STATUS_WORKING = 'Working';
    public static final String COLLECTION_CASE_STATUS_ACCOMMODATION = 'Accommodation';

    public static final String FREQUENCY_DAILY = 'Daily';
    public static final String FREQUENCY_WEEKLY = 'Weekly';
    public static final String FREQUENCY_BI_WEEKLY = 'Bi-weekly';
    public static final String FREQUENCY_MONTHLY = 'Monthly';
    public static final String RETURN_REASON_CODE_01 = 'R01';
    public static final String RETURN_REASON_CODE_09 = 'R09';
    public static final String RETURN_REASON_CODE_BLANK = '';
    public static final Integer TOTAL_OUTSTANDING_REPAYMENT_AMOUNT = 50000;
    public static final Integer TOTAL_OUTSTANDING_REPAYMENT_AMOUNT_0 = 0;
    public static final Integer NUMBER_OF_MISSED_PAYMENTS_3 = 3;
    public static final Integer NUMBER_OF_MISSED_PAYMENTS_2 = 2;
    public static final Integer NUMBER_OF_MISSED_PAYMENTS_1 = 1;

    public static final String LOW_BALANCE_QUEUE = 'LOW BALANCE';
    public static final String HIGH_BALANCE_QUEUE = 'HIGH BALANCE';

    public static final String IN_PROGRESS_PROMISE = 'In Progress';
    public static final String KEPT_PROMISE = 'Kept';
    public static final String BROKEN_PROMISE = 'Broken';

    public static final String PAYMENT_ARRANGEMENT_NOTIFICATION = 'Payment Arrangement Notification';

    public static final String MISSED_CATCHUP_NOTIFICATION = 'Missed Catch Up Payment';
    public static final String MISSED_ACCOMODATION_NOTIFICATION = 'Promise Broken';
    public static final String MISSED_SETTLEMENT_NOTIFICATION = 'Missed Settlement Payment';

    public static final String CATCHUP_EXPIRE_NOTIFICATION = 'Catch up period expired';

    /* --------- Payment Arrangement - Constants ------------ */
    @AuraEnabled public final String PAYMENT_ARRANGEMENT_TYPE_PROMISE_TO_PAY = 'Promise to Pay';
    @AuraEnabled public final String PAYMENT_ARRANGEMENT_TYPE_JUDGEMENT = 'Judgment';
    @AuraEnabled public final String PAYMENT_ARRANGEMENT_TYPE_CATCH_UP = 'Catch Up';
    @AuraEnabled public final String PAYMENT_ARRANGEMENT_TYPE_SETTLEMENT = 'Settlement';
    @AuraEnabled public final String PAYMENT_ARRANGEMENT_TYPE_ACCOMMODATION = 'Accommodation';

    @AuraEnabled public final String PAYMENT_MODE_ACH = 'ACH';
    @AuraEnabled public final String PAYMENT_MODE_WIRE = 'WIRE';
    @AuraEnabled public final String PAYMENT_MODE_CHECK = 'CHECK';
    @AuraEnabled public final String PAYMENT_MODE_MONEY_ORDER = 'MONEY ORDER';
    @AuraEnabled public final String PAYMENT_MODE_CREDIT_CARD = 'CREDIT CARD';

    @AuraEnabled public final String PROMISE_IN_PROGRESS = 'In Progress';
    @AuraEnabled public final String PROMISE_KEPT= 'Kept';
    @AuraEnabled public final String PROMISE_BROKEN = 'Broken';

    @AuraEnabled public final String APS_TYPE_ONE_TIME = 'ONE TIME';
    @AuraEnabled public final String APS_TYPE_RECURRING = 'RECURRING';

    @AuraEnabled public final String APS_AMOUNT_TYPE_FIXED_AMOUNT= 'FIXED AMOUNT';
    @AuraEnabled public final String APS_AMOUNT_TYPE_LAST_BILLED_AMOUNT= 'LAST BILLED AMOUNT';
    @AuraEnabled public final String APS_AMOUNT_TYPE_CURRENT_PAYMENT_AMOUNT= 'CURRENT PAYMENT AMOUNT';
    @AuraEnabled public final String APS_AMOUNT_TYPE_OLDEST_UNPAID_BILL_AMOUNT= 'OLDEST UNPAID BILL AMOUNT';
    @AuraEnabled public final String APS_AMOUNT_TYPE_TOTAL_OUTSTANDING_BILL_AMOUNT = 'TOTAL OUTSTANDING BILL AMOUNT';

    @AuraEnabled public final String JUDGEMENT_STATUS = 'Judgement';
    @AuraEnabled public final String JUDGEMENT_SUB_STATUS = 'Judgement Awarded';

    @AuraEnabled public final String SETTLEMENT_PLAN_STATUS = 'Settlement Plan';
    @AuraEnabled public final String SETTLEMENT_PLAN_SUB_STATUS = 'Settlement Plan';

    @AuraEnabled public final String CATUP_BAD_STANDING_STATUS = 'Bad Standing';
    @AuraEnabled public final String CATUP_SCHEDULED_SUB_STATUS = 'Catch Up Payments Scheduled';

    @AuraEnabled public final String DAILY_FREQUENCY = 'Daily';
    @AuraEnabled public final String WEEKLY_FREQUENCY = 'Weekly';
    @AuraEnabled public final String MONTHLY_FREQUENCY = 'Monthly';
    @AuraEnabled public final String BI_WEEKLY_FREQUENCY = 'Bi-weekly';
    @AuraEnabled public final String SEMI_MONTHLY_FREQUENCY = 'Semi-Monthly';

    @AuraEnabled public final String SUCCESS = 'Success';

    public static final String CONGA_GENERATE_DOCUMENT_URL = 'https://composer.congamerge.com?serverUrl=[SFDC_BASEURL]/services/Soap/u/37.0/[ORG_ID]&Id=[REC_ID]&SelectTemplates=1&TemplateGroup=Collections&CSRecipient1=[RECIPIENT_ID]&SC1=SalesforceFile&CSVisible=1&FP0=1&queryid=[Collection_Case_Query]';
    public static String SFDC_BASEURL_KEY = '[SFDC_BASEURL]';
    public static String SESSION_ID = '[SessionId]';
    public static String ORG_ID_KEY = '[ORG_ID]';
    public static String REC_ID_KEY = '[REC_ID]';
    public static String RECIPIENT_ID_KEY = '[RECIPIENT_ID]';
    public static String QUERY_IDS_KEY = '[QueryIds]';
    public static String CONGA_QUERY_TYPE = 'Loan Agreement%';
    public static String APP_NAME_KEY = '[APP_Name]';
    public static String COLLECTION_CASE_QUERY_KEY = '[Collection_Case_Query]';
}