@isTest
public class CLSBPPortalConstantsTests {

    @isTest
    private static void cLSBPPortalConstantssPaymentPayoffResponses() {

        Test.startTest();
            Object x = CLSBPPortalConstants.UNAUTHORIZED_ACTION;
                x = CLSBPPortalConstants.LOAN_INFO;
                x = CLSBPPortalConstants.SOMETHING_WENT_WRONG;
                x = CLSBPPortalConstants.APPLICATION_ID;
                x = CLSBPPortalConstants.BI_BASIC_INFO;
                x = CLSBPPortalConstants.BI_BINNING_ADDRESS;
                x = CLSBPPortalConstants.BI_MAILING_ADDRESS;
                x = CLSBPPortalConstants.BI_ESTD_DETAILS;
                x = CLSBPPortalConstants.APP_ID_IS_NULL;
                x = CLSBPPortalConstants.PARTY_TYPE;
                x = CLSBPPortalConstants.CLIENT_TYPE;
                x = CLSBPPortalConstants.BUSINESS;
                x = CLSBPPortalConstants.INDIVIDUAL;
                x = CLSBPPortalConstants.COBORROWER_ACCOUNT_ID;
                x = CLSBPPortalConstants.COBORROWER_CONTACT_ID;
                x = CLSBPPortalConstants.IND_ACC_DETAILS;
                x = CLSBPPortalConstants.COLLATERAL_TYPES;
                x = CLSBPPortalConstants.ADD_OWNER;
                x = CLSBPPortalConstants.ADD_COLLATERALS;
                x = CLSBPPortalConstants.PARTY_LABLE;
                x = CLSBPPortalConstants.ASSET;
                x = CLSBPPortalConstants.LIABILITY;
                x = CLSBPPortalConstants.INCOME;
                x = CLSBPPortalConstants.EXPENSE;
                x = CLSBPPortalConstants.SELECTED_STATUS;
                x = CLSBPPortalConstants.COMPLETED;
                x = CLSBPPortalConstants.OUTSTANDING;
                x = CLSBPPortalConstants.SUBMITTED;
                x = CLSBPPortalConstants.SEARCH_DETAILS;
                x = CLSBPPortalConstants.REVIEW_COMMENT;
                x = CLSBPPortalConstants.TASK_ID;
                x = CLSBPPortalConstants.RECENT;
        Test.stopTest();

        System.assert(x != null);
    }
}