@isTest
private class CustomConstantsTests {

    @isTest
    private static void customConstantsPaymentPayoffResponses() {

        Test.startTest();
            Object x = CustomConstants.APPLICATION_ID;
            x = CustomConstants.BORROWER;
            x = CustomConstants.CO_BORROWER;
            x = CustomConstants.COSIGNER;
            x = CustomConstants.HYPOTHECATOR;
            x = CustomConstants.INDIVIDUAL;
            x = CustomConstants.REJECTED;
            x = CustomConstants.NEWCHECKLISTGENERATED;
            x = CustomConstants.BORROWERAGECHECK;
            x = CustomConstants.COBORROWERAGECHECK;
            x = CustomConstants.BORROWERCITIZENSHIPCHECK;
            x = CustomConstants.COBORROWERCITIZENSHIPCHECK;
            x = CustomConstants.FACT_ACTIVE_DUTY;
            x = CustomConstants.SERVICE_MEMBER;
            x = CustomConstants.ACTIVE_DUTY;
            x = CustomConstants.INSIDER;
            x = CustomConstants.RETIRED;
            x = CustomConstants.MILITARY_ENLISTED;
            x = CustomConstants.MILITARY_OFFICER;
            x = CustomConstants.CREDIT_DISABILITY;
            x = CustomConstants.CREDIT_LIFE;
            x = CustomConstants.GAP;
            x = CustomConstants.INVOLUNTARY;
            x = CustomConstants.WAIVE_PROTECTION;
            x = CustomConstants.NO_PAYMENT_PROTECTION;
            x = CustomConstants.RELIEVE_LENDER_PROTECTION;
            x = CustomConstants.PORTAL_STAGE;
            x = CustomConstants.PORTAL_SUB_STAGE;
            x = CustomConstants.NEWSUBMITTED;
            x = CustomConstants.CONSUMER_UNSECURED;
            x = CustomConstants.CONSUMER_SECURED;
            x = CustomConstants.PROOF_OF_INCOME;
            x = CustomConstants.SUPPORTING_DOC;
            x = CustomConstants.STATUS_NEW_SCORECARD_GENERATED;
            x = CustomConstants.MINIMUM;
            x = CustomConstants.MAXIMUM;
            x = CustomConstants.AVERAGE;
            x = CustomConstants.RETURN_MESSAGE;
            x = CustomConstants.CONSUMER_SECURED_PURCHASE;
            x = CustomConstants.CONSUMER_SECURED_REFINANCE;
            x = CustomConstants.CONSUMER_SECURED_SAVINGS_CD;
            x = CustomConstants.CONSUMER_CREDIT_CARD;
            x = CustomConstants.CONSUMER_UNSECURED_LOAN;
            x = CustomConstants.JOINT;
            x = CustomConstants.SINGLE;
            x = CustomConstants.IUI;
            x = CustomConstants.LIFE;
            x = CustomConstants.DISABILITY;
            x = CustomConstants.GAP_INSURANCE;
            x = CustomConstants.CDI_JOInt;
            x = CustomConstants.CDI_SINGLE;
            x = CustomConstants.DLI_SINGLE;
            x = CustomConstants.DLI_JOINT;
            x = CustomConstants.ILD_JOINT;
            x = CustomConstants.ILD_SINGLE;
            x = CustomConstants.CD_JOINT;
            x = CustomConstants.CD_SINGLE;
            x = CustomConstants.DL_JOINT;
            x = CustomConstants.DL_SINGLE;
            x = CustomConstants.DI_JOINT;
            x = CustomConstants.DI_SINGLE;
            x = CustomConstants.ID_JOINT;
            x = CustomConstants.ID_SINGLE;
            x = CustomConstants.CI_JOINT;
            x = CustomConstants.CI_SINGLE;
            x = CustomConstants.IL_JOINT;
            x = CustomConstants.IL_SINGLE;
            x = CustomConstants.DISABILITY_JOINT;
            x = CustomConstants.DISABILITY_SINGLE;
            x = CustomConstants.CREDIT_LIFE_JOINT;
            x = CustomConstants.CREDIT_LIFE_SINGLE;
        Test.stopTest();

        System.assert(X != null);
    }
}